import React from 'react';
import {
  Pool,
  FitnessCenter,
  LocalParking,
  Elevator,
  Security,
  AcUnit,
  Whatshot,
  LocalLaundryService,
  Kitchen,
  Balcony,
  Park,
  OutdoorGrill,
  SportsTennis,
  SportsBasketball,
  ChildCare,
  Weekend,
  DirectionsBike,
  Pets,
  People,
  Business,
  MeetingRoom,
  MoveToInbox,
  Store,
  Deck,
  HotTub,
  Spa,
  Wifi,
  Home,
  Tv,
  Videocam,
  WineBar,
  Theaters,
  SportsGolf,
  SelfImprovement,
  Waves,
  SolarPower,
  EvStation,
  Opacity,
  Power,
  Recycling,
  HelpOutline,
} from '@mui/icons-material';
import { useTheme } from '@mui/material/styles';

// Normalize amenity names for mapping
const normalizeAmenity = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]/gi, '');

const theme = useTheme();

export const amenityIconMap: Record<string, React.ReactNode> = {
  swimmingpool: <Pool color='info'/>,
  fitnesscenter: <FitnessCenter color='info'/>,
  parkingspace: <LocalParking color='primary'/>,
  elevator: <Elevator color='secondary'/>,
  securitysystem: <Security color='primary'/>,
  airconditioning: <AcUnit color='action'/>,
  heatingsystem: <Whatshot color='error'/>,
  washerdryer: <LocalLaundryService color='info'/>,
  dishwasher: <Kitchen color='info'/>,
  balconypatio: <Balcony color='info'/>,
  garden: <Park color='success'/>,
  bbqarea: <OutdoorGrill color='info'/>,
  tenniscourt: <SportsTennis color='info'/>,
  basketballcourt: <SportsBasketball color='action'/>,
  childrensplayground: <ChildCare color='action'/>,
  outdoorseatingarea: <Weekend color='action'/>,
  bikestorage: <DirectionsBike color='info'/>,
  petarea: <Pets color='disabled'/>,
  communitylounge: <People color='info'/>,
  businesscenter: <Business color='info'/>,
  conferenceroom: <MeetingRoom color='info'/>,
  packagereceiving: <MoveToInbox color='info'/>,
  storageunit: <Store color='disabled'/>,
  rooftopterrace: <Deck color='primary'/>,
  spahottub: <HotTub color='secondary'/>,
  sauna: <Spa color='warning'/>,
  highspeedinternet: <Wifi color='success'/>,
  smarthomefeatures: <Home color='info'/>,
  cabletvready: <Tv color='primary'/>,
  videointercom: <Videocam color='primary'/>,
  winecellar: <WineBar color='secondary'/>,
  movietheater: <Theaters color='info'/>,
  golfsimulator: <SportsGolf color='info'/>,
  yogastudio: <SelfImprovement color='info'/>,
  indoorpool: <Waves color='info'/>,
  solarpanels: <SolarPower color='info'/>,
  electricvehiclecharging: <EvStation color='info'/>,
  waterfiltrationsystem: <Opacity color='info'/>,
  backupgenerator: <Power color='primary'/>,
  recyclingcenter: <Recycling color='success'/>,
};

// Helper to get icon by amenity name (case-insensitive, fallback to HelpOutline)
export const getAmenityIcon = (name: string) =>
  amenityIconMap[normalizeAmenity(name)] || <HelpOutline />;