import { Stack, Typography } from '@mui/material';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import IconButton from '@mui/material/IconButton';
import CloseIcon from '@mui/icons-material/Close';
import OTPInput from '../ControlledComponents/OTPInputField';
import LoadingButton from '@mui/lab/LoadingButton';

interface OtpPrompt {
	open: boolean;
	onCancel: React.MouseEventHandler<HTMLButtonElement> | (() => void);
	onVerifyOtpClick: React.MouseEventHandler<HTMLButtonElement> | undefined;
	verifyOtp: () => void;
	setOtp: React.Dispatch<React.SetStateAction<string>>;
	otp: string;
	otpError: string;
	verifying: boolean;
}
const OTPPrompt = ({
	open,
	onCancel,
	onVerifyOtpClick,
	verifyOtp,
	setOtp,
	otp,
	otpError,
	verifying,
}: OtpPrompt) => {
	return (
		<Dialog open={open}>
			<IconButton
				sx={{
					position: 'absolute',
					right: 8,
					top: 8,
				}}
				onClick={onCancel}
			>
				<CloseIcon />
			</IconButton>
			<Stack direction={'column'} spacing={3} sx={{ p: 4 }}>
				{/* Add Icon here later */}

				<Stack
					direction='column'
					gap={2}
					sx={{
						alignItems: 'center',
						justifyContent: 'center',
						textAlign: 'center',
					}}
				>
					<Typography variant='h4'>Two-Factor Authentication</Typography>
					<Typography variant='body1'>
						Enter the 6-digit code generated by your authentication app to
						confirm your identity.
					</Typography>
					<OTPInput
						value={otp}
						separator={<span>&nbsp;</span>}
						onChange={setOtp}
						length={6}
						onEnterKeyPress={verifyOtp}
					/>
					{otpError && <Typography color='error'>{otpError}</Typography>}
				</Stack>
				<Stack
					direction={'row'}
					spacing={1}
					sx={{
						justifyContent: 'flex-end',
					}}
				>
					<Button variant='outlined' onClick={onCancel}>
						Cancel
					</Button>
					<LoadingButton
						onClick={onVerifyOtpClick}
						loading={verifying}
						loadingIndicator='verifying...'
						variant='contained'
					>
						Verify
					</LoadingButton>
				</Stack>
			</Stack>
		</Dialog>
	);
};

export default OTPPrompt;
