# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.55/docs/schemas/v1/definitions.json#properties/Theme

apiVersion: v1
kind: theme
spec:
  options:
    palette:
      mode: light
      primary:
        main: '#002147'
        contrastText: '#fff'
      secondary:
        main: '#005CFF'
        contrastText: '#fff'
