export const leases = [
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Expiring',
		tenant: 'Aisha R',
		property: 'City High',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Expiring',
		tenant: 'Aisha R',
		property: 'City High',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Expiring',
		tenant: 'Aisha R',
		property: 'City High',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Over Due',
		tenant: 'Aisha R',
		property: 'Hybib Apartment',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Landmark House',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Expiring',
		tenant: 'Aisha R',
		property: 'City High',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Resolved Avenue',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Over Due',
		tenant: 'Aisha R',
		property: 'Hybib Apartment',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Active',
		tenant: 'Aisha R',
		property: 'Gateway Garden',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
	{
		status: 'Over Due',
		tenant: 'Aisha R',
		property: 'Hybib Apartment',
		unit: '034',
		leaseStart: 'April 4, 2024',
		leaseEnd: 'April 4, 2024',
	},
];
