import { OptionsType } from '../../components/Filter/Filter';
import {
	ReverseIcon,
	AscendIcon,
	TopBottom,
} from '../../components/Icons/CustomIcons';

export const data = [
	{
		title: '5 Bedroom House',
		address: '16B Ibrahim Fadoyin Street, Ikosi Ketu',
		bedrooms: 5,
		bathrooms: 5,
		sqm: 1000,
		type: 'Residential Housing',
		status: 'For Sale',
		image: '../../../src/assets/images/Rectangle 157.jpg',
		propertyType: 'Bungalow',
		unitType: 'Multi Unit',
		purpose: 'Sell',
	},
	{
		title: 'Landmark Estate',
		address: 'Engineering Close, off Idowu Street, Victoria Island, Lagos',
		bedrooms: 5,
		bathrooms: 5,
		sqm: 800,
		type: 'Residential Housing',
		status: 'For Rent',
		image: '../../../src/assets/images/Rectangle 157.jpg',
		propertyType: 'Duplex',
		unitType: 'Single Unit',
		purpose: 'Lease',
	},
	{
		title: 'Next Estate',
		address: 'Engineering Close, off Idowu Street, Victoria Island, Lagos',
		bedrooms: 5,
		bathrooms: 5,
		sqm: 800,
		type: 'Residential Housing',
		status: 'For Rent',
		image: '../../../src/assets/images/Rectangle 157.jpg',
		propertyType: 'Apartment',
		unitType: 'Single Unit',
		purpose: 'Lease',
	},
	{
		title: 'Terrace Estate',
		address: 'Engineering Close, off Idowu Street, Victoria Island, Lagos',
		bedrooms: 5,
		bathrooms: 5,
		sqm: 800,
		type: 'Residential Housing',
		status: 'For Rent',
		image: '../../../src/assets/images/Rectangle 157.jpg',
		propertyType: 'Terrace',
		unitType: 'Multi Unit',
		purpose: 'Sell',
	},
	{
		title: 'Land Estate',
		address: 'Engineering Close, off Idowu Street, Victoria Island, Lagos',
		bedrooms: 5,
		bathrooms: 5,
		sqm: 800,
		type: 'Residential Housing',
		status: 'For Rent',
		image: '../../../src/assets/images/Rectangle 157.jpg',
		propertyType: 'Land',
		unitType: 'Single Unit',
		purpose: 'Lease',
	},
];

export const filterOptions: OptionsType = [
	{
		id: '',
		title: '',
		options: [
			{ label: '', Icon: '', value: '' },
			{ label: '', Icon: '', value: '' },
		],
	},
];
