export const API_TAGS = {
    PROPERTY: 'Property',
    PROPERTY_METADATA: 'Property-Metadata',
    TENANT: 'Tenant',
    LEASE: 'Lease',
    LEASE_METADATA: 'Lease-Metadata',
    TENANT_FILTER_METADATA: 'Tenant-Filter-Metadata',
    ORGANIZATION: 'Organization',
    NOTIFICATION: 'Notification',
    NOTIFICATION_COUNT: 'Notification-Count',
    USER: 'User',
    SETTINGS:"settings",
    DASHBOARD_METRICS: 'Dashboard-Metrics',
    DASHBOARD_REVENUE_REPORT: 'Dashboard-Revenue-Report',
    PROPERTIES_AND_TENANTS: 'Properties-And-Tenants',
    ACTIVITY: 'Activity',
    ORGANIZATION_METRICS: 'Organization-Metrics',
    ORGANIZATION_COMPARATIVE_METRICS: 'Organization-Comparative-Metrics',
  } as const;
export const ALL_TAGS = Object.values(API_TAGS);