# name: Deploy Tenant Portal
# on:
#   push:
#     # branches:
#       # - dev
#     # paths:
#       # - "apps/tenant-portal/**"
#       # - "packages/**"
# env:
#   VITE_BASE_URL_DEV: ${{ vars.VITE_BASE_URL_DEV }}
#   VITE_APPLICATION_NAME: klubiq-tenant-portal
#   NODE_ENV: ${{ github.env }}
#   VITE_NODE_ENV: ${{ github.env }}
#   VITE_IDB_VERSION: ${{ vars.VITE_IDB_VERSION }}
#   REACT_APP_DATA_CACHE: ${{ vars.REACT_APP_DATA_CACHE }}
#   REACT_APP_ALLOWED_ORIGINS: ${{ vars.REACT_APP_ALLOWED_ORIGINS }}
#   REACT_APP_PUBLIC_CACHED_PATHS: ${{ vars.REACT_APP_PUBLIC_CACHED_PATHS }}
#   REACT_APP_CACHE_EXPIRATION_TIME: ${{ vars.REACT_APP_CACHE_EXPIRATION_TIME }}
#   VITE_THEME_SWITCH_ENABLED: ${{ vars.VITE_THEME_SWITCH_ENABLED }}

#   APP: klubiq-tenat-portal
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build Project
#         run: |
#           npm install --include=optional
#           npm run buildUIC || exit 1
#           npm run buildTP || exit 1
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: artifacts
#           path: |
#             apps/tenant-portal/dist/
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download dev artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: artifacts
#           path: artifacts/dist
#       - name: Deploy to Lightsail
#         uses: easingthemes/ssh-deploy@main
#         with:
#           REMOTE_HOST: ${{ secrets.SSH_HOST }}
#           REMOTE_USER: ${{ secrets.SSH_USERNAME }}
#           SSH_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_CERT }}
#           SOURCE: 'artifacts/'
#           EXCLUDE: '/node_modules/, node_modules, /node_modules'
#           TARGET: ${{ secrets.TARGET_DIR }}
#           SCRIPT_BEFORE: |
#             sudo chown $USER ${{ secrets.TARGET_DIR }}
#             cd ${{ secrets.TARGET_DIR }}


# #npm ci --omit=dev && npm cache clean --force
